### ISSUE TITLE
crash on copy on Mac

### ISSUE THREAD

**Issue by pankona** [pankona/hashira#107]
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/pankona/orderedmap.(*OrderedMap).GetByIndex(...)
	/home/pankona/go/pkg/mod/github.com/pankona/orderedmap@v0.0.0-20190220081458-0d2a73efbdac/orderedmap.go:108
main.(*View).FocusedTask(...)
	/home/pankona/go/src/github.com/pankona/hashira/cmd/hashira-cui/view.go:286
main.(*View).selectFocusedTask(0xc00012c120, 0xc000066958, 0x1)
	/home/pankona/go/src/github.com/pankona/hashira/cmd/hashira-cui/view.go:277 +0x3d0
main.(*View).KeySpace(0xc00012c120, 0xc00012c090, 0xc0001bc200, 0xc0000bdc1a, 0x3)
	/home/pankona/go/src/github.com/pankona/hashira/cmd/hashira-cui/keybinding.go:102 +0x2b
main.(*View).KeySpace-fm(0xc00012c090, 0xc0001bc200, 0x0, 0x0)
	/home/pankona/go/src/github.com/pankona/hashira/cmd/hashira-cui/keybinding.go:40 +0x3e
github.com/pankona/gocui.(*Gui).execKeybinding(0xc00012c090, 0xc0001bc200, 0xc000114900, 0x1, 0x0, 0xc0000bdc1a)
	/home/pankona/go/pkg/mod/github.com/pankona/gocui@v0.3.1-0.20190107094646-a6233010013f/gui.go:703 +0x3e
github.com/pankona/gocui.(*Gui).execKeybindings(0xc00012c090, 0xc0001bc200, 0xc0000bdc28, 0xc0001b2c00, 0x0, 0x0)
	/home/pankona/go/pkg/mod/github.com/pankona/gocui@v0.3.1-0.20190107094646-a6233010013f/gui.go:689 +0xef
github.com/pankona/gocui.(*Gui).onKey(0xc00012c090, 0xc0000bdc28, 0x0, 0x0)
	/home/pankona/go/pkg/mod/github.com/pankona/gocui@v0.3.1-0.20190107094646-a6233010013f/gui.go:650 +0x1b0
github.com/pankona/gocui.(*Gui).handleEvent(0xc00012c090, 0xc0000bdc28, 0x3, 0x0)
	/home/pankona/go/pkg/mod/github.com/pankona/gocui@v0.3.1-0.20190107094646-a6233010013f/gui.go:431 +0x40
github.com/pankona/gocui.(*Gui).consumeevents(0xc00012c090, 0xc0000bdd68, 0x0)
	/home/pankona/go/pkg/mod/github.com/pankona/gocui@v0.3.1-0.20190107094646-a6233010013f/gui.go:413 +0x1fd
github.com/pankona/gocui.(*Gui).MainLoop(0xc00012c090, 0x15b65e0, 0xc000022088)
	/home/pankona/go/pkg/mod/github.com/pankona/gocui@v0.3.1-0.20190107094646-a6233010013f/gui.go:399 +0x1f3
main.main()
	/home/pankona/go/src/github.com/pankona/hashira/cmd/hashira-cui/main.go:111 +0x4f4
```

**Comment by pankona** [comment]
another crash log
```
hashira-cui 
panic: failed to insert [aTRPOStep実装] to [Done]. fatal

goroutine 1 [running]:
log.Panicln(0xc0000bded8, 0x1, 0x1)
    /home/pankona/sdk/go1.11.5/src/log/log.go:340 +0xc0
main.main()
    /home/pankona/go/src/github.com/pankona/hashira/cmd/hashira-cui/main.go:113 +0x579
```
