### ISSUE TITLE
Crash on OrderedMap

### ISSUE THREAD

**Issue by pankona** [pankona/hashira#121]
```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/pankona/orderedmap.(*OrderedMap).Insert(0xc00055c200, 0x15af160, 0xc00014ab40, 0xffffffffffffffff, 0x0, 0x2)
        /Users/masa/go/src/github.com/pankona/orderedmap/orderedmap.go:44 +0x52d
main.(*View).moveTaskPlaceTo(0xc0001b4090, 0xc00014ab40, 0xc0001681c0, 0xffffffffffffffff, 0xc00016c308, 0xc0000ebba8)
        /Users/masa/go/src/github.com/pankona/hashira/cmd/hashira-cui/view.go:138 +0x22e
main.(*View).Left(0xc0001b4090, 0xc0001b6058, 0x0)
        /Users/masa/go/src/github.com/pankona/hashira/cmd/hashira-cui/view.go:103 +0xbc
main.(*View).KeyLeft(0xc0001b4090, 0xc0001b4000, 0xc0002ea300, 0xc0000ebd5c, 0x2)
        /Users/masa/go/src/github.com/pankona/hashira/cmd/hashira-cui/keybinding.go:51 +0x2b
main.(*View).KeyLeft-fm(0xc0001b4000, 0xc0002ea300, 0x1, 0x0)
        /Users/masa/go/src/github.com/pankona/hashira/cmd/hashira-cui/keybinding.go:26 +0x3e
github.com/pankona/gocui.(*Gui).execKeybinding(0xc0001b4000, 0xc0002ea300, 0xc000158870, 0x1, 0xc0000b68e8, 0xc0000ebd5c)
        /Users/masa/go/src/github.com/pankona/gocui/gui.go:703 +0x3e
github.com/pankona/gocui.(*Gui).execKeybindings(0xc0001b4000, 0xc0002ea300, 0xc0000ebd68, 0x13d0a4a, 0x0, 0x0)
        /Users/masa/go/src/github.com/pankona/gocui/gui.go:689 +0xef
github.com/pankona/gocui.(*Gui).onKey(0xc0001b4000, 0xc0000ebd68, 0xc0005481c0, 0xc00015a070)
        /Users/masa/go/src/github.com/pankona/gocui/gui.go:650 +0x1b0
github.com/pankona/gocui.(*Gui).handleEvent(0xc0001b4000, 0xc0000ebd68, 0x2, 0x0)
        /Users/masa/go/src/github.com/pankona/gocui/gui.go:431 +0x40
github.com/pankona/gocui.(*Gui).MainLoop(0xc0001b4000, 0x15b4540, 0xc0000a8010)
        /Users/masa/go/src/github.com/pankona/gocui/gui.go:391 +0x2d2
main.main()
        /Users/masa/go/src/github.com/pankona/hashira/cmd/hashira-cui/main.go:111 +0x4f4
```

**Comment by pankona** [comment]
- Doingから Done に１項目（スペースキー）でつかんで動かす
- 右に動かした後、左側（Doing側）に動す
- 上記エラー発生

**Comment by pankona** [comment]
How to reproduce:
- grab a item with space key
- whle grabbing, press i/I to move the task to another pane
  - then the item move to another pane, but the item is still grabbing, but selected pane is not changed
- change focus of pane with l or h
