### ISSUE TITLE
Crash on appending wide character to existing task

### ISSUE THREAD

**Issue by pankona** [pankona/hashira#83]
- How to reproduce
  - register a task
  - edit task
    - insert wide characters to stick out the insert field, and press enter
    - crash

here's stack trace on crash:

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/pankona/hashira/vendor/github.com/pankona/gocui.(*View).writeRune(0xc00013c200, 0x27, 0x0, 0x51fa, 0x3, 0x0)
	/home/pankona/go/src/github.com/pankona/hashira/vendor/github.com/pankona/gocui/edit.go:304 +0x724
github.com/pankona/hashira/vendor/github.com/pankona/gocui.(*View).EditWrite(0xc00013c200, 0xc0000051fa)
	/home/pankona/go/src/github.com/pankona/hashira/vendor/github.com/pankona/gocui/edit.go:62 +0x5b
github.com/pankona/hashira/vendor/github.com/pankona/gocui.simpleEditor(0xc00013c200, 0x51fa00310000, 0xc000317c00)
	/home/pankona/go/src/github.com/pankona/hashira/vendor/github.com/pankona/gocui/edit.go:37 +0x1bb
github.com/pankona/hashira/vendor/github.com/pankona/gocui.EditorFunc.Edit(0x9424c8, 0xc00013c200, 0x51fa00000000, 0xc0001c6200)
	/home/pankona/go/src/github.com/pankona/hashira/vendor/github.com/pankona/gocui/edit.go:27 +0x4b
main.(*editor).Edit(0xd36260, 0xc00013c200, 0x51fa00310000, 0x0)
	/home/pankona/go/src/github.com/pankona/hashira/cmd/hashira-cui/editor.go:29 +0x74
github.com/pankona/hashira/vendor/github.com/pankona/gocui.(*Gui).onKey(0xc0001b8000, 0xc000317c28, 0xc000317c10, 0x7c2f91)
	/home/pankona/go/src/github.com/pankona/hashira/vendor/github.com/pankona/gocui/gui.go:658 +0x238
github.com/pankona/hashira/vendor/github.com/pankona/gocui.(*Gui).handleEvent(0xc0001b8000, 0xc000317c28, 0x3, 0x0)
	/home/pankona/go/src/github.com/pankona/hashira/vendor/github.com/pankona/gocui/gui.go:431 +0x40
github.com/pankona/hashira/vendor/github.com/pankona/gocui.(*Gui).consumeevents(0xc0001b8000, 0xc000317d68, 0x0)
	/home/pankona/go/src/github.com/pankona/hashira/vendor/github.com/pankona/gocui/gui.go:413 +0x1fd
github.com/pankona/hashira/vendor/github.com/pankona/gocui.(*Gui).MainLoop(0xc0001b8000, 0x9a3c80, 0xc00009c010)
	/home/pankona/go/src/github.com/pankona/hashira/vendor/github.com/pankona/gocui/gui.go:399 +0x1f3
main.main()
	/home/pankona/go/src/github.com/pankona/hashira/cmd/hashira-cui/main.go:111 +0x4f4
```

**Comment by pankona** [comment]
fix this issue by fixing forked gocui library.
update dependencies to apply the modification.
